/**
 * Curated halal restaurant data — matches muslim-traveler-app food.js exactly.
 * Static list: no API, no CORS issues, always loads instantly.
 */
export const RESTAURANTS = [
  {
    id: 'my-01',
    name: 'Nasi Lemak Antarabangsa',
    country: 'Malaysia',
    city: 'Kuala Lumpur',
    cuisine: 'Malaysian',
    description: 'Iconic 24-hour nasi lemak stall in Chow Kit that has been serving fragrant coconut rice with rendang and sambal for decades. A must-visit KL institution beloved by locals and tourists alike.',
    viralReason: 'Featured in multiple travel vlogs and food documentaries. Queues form even at 3 AM.',
    instagram: '@nasilemakantarabangsa',
    emoji: '🍚',
    tags: ['24-hour', 'Street Food', 'Local Favourite', 'Budget'],
  },
  {
    id: 'my-02',
    name: 'Sup Hameed',
    country: 'Malaysia',
    city: 'Penang',
    cuisine: 'Malay-Indian',
    description: 'World-famous sup tulang (bone soup) and sup gearbox stall at Penang Road. Rich, spiced bone broth that has attracted visitors from across Southeast Asia.',
    viralReason: 'Went viral on TikTok and YouTube for the spectacular bone marrow soup. Often cited in top Penang food lists.',
    instagram: '@suphameedpenang',
    emoji: '🍖',
    tags: ['Soup', 'Street Food', 'Viral TikTok', 'Heritage'],
  },
  {
    id: 'id-01',
    name: 'Sate Khas Senayan',
    country: 'Indonesia',
    city: 'Jakarta',
    cuisine: 'Indonesian',
    description: "One of Jakarta's most celebrated satay restaurants, serving perfectly marinated and grilled skewers of chicken and beef with legendary peanut sauce and lontong since 1968.",
    viralReason: 'A Jakarta institution featured in every food guide. Long queues are the norm on weekends.',
    instagram: '@satekhassenayan',
    emoji: '🍢',
    tags: ['Satay', 'Heritage', 'Family Dining', 'Must-Try'],
  },
  {
    id: 'id-02',
    name: 'Warung Mak Beng',
    country: 'Indonesia',
    city: 'Bali',
    cuisine: 'Balinese',
    description: 'A humble warung in Sanur, Bali, serving a single legendary dish: fried fish with fish soup, rice, and sambal. Simple, extraordinary, and always packed since 1941.',
    viralReason: "Called 'the best meal in Bali' by countless travellers. Featured by international food critics.",
    instagram: '@warungmakbeng_bali',
    emoji: '🐟',
    tags: ['Seafood', 'Heritage', 'Simple & Delicious', 'Cash Only'],
  },
  {
    id: 'tr-01',
    name: 'Hafiz Mustafa 1864',
    country: 'Turkey',
    city: 'Istanbul',
    cuisine: 'Turkish Desserts',
    description: 'A legendary Istanbul confectionery operating since 1864, renowned for its baklava, lokum (Turkish delight), and traditional sweets. A sweet paradise for travellers in the heart of Istanbul.',
    viralReason: 'Instagram-famous for its stunning baklava displays. One of Turkey\'s most-photographed dessert spots.',
    instagram: '@hafizmustafa1864',
    emoji: '🍯',
    tags: ['Dessert', 'Heritage', 'Baklava', 'Iconic'],
  },
  {
    id: 'tr-02',
    name: 'Çiya Sofrası',
    country: 'Turkey',
    city: 'Istanbul',
    cuisine: 'Anatolian',
    description: 'A celebrated restaurant in Kadıköy market serving rare, forgotten Anatolian recipes. Chef Musa Dağdeviren has been lauded globally for preserving Turkey\'s culinary heritage.',
    viralReason: "Featured in Netflix's Chef's Table. Hailed as one of the world's most important restaurants.",
    instagram: '@ciyasofras',
    emoji: '🥘',
    tags: ['Anatolian', 'Fine Dining', 'Netflix Featured', 'Cultural'],
  },
  {
    id: 'ae-01',
    name: 'Al Fanar Restaurant',
    country: 'UAE',
    city: 'Dubai',
    cuisine: 'Emirati',
    description: "Dubai's go-to destination for authentic Emirati cuisine. Set in a traditional lighthouse-themed decor, it serves dishes like Harees, Machboos, and Luqaimat in a warm heritage setting.",
    viralReason: 'Top recommendation for tourists wanting to experience real Emirati food culture. Frequently featured in Dubai travel guides.',
    instagram: '@alfanarrestaurant',
    emoji: '🏺',
    tags: ['Emirati', 'Heritage Dining', 'Cultural Experience', 'Tourist Favourite'],
  },
  {
    id: 'ae-02',
    name: 'Operation: Falafel',
    country: 'UAE',
    city: 'Dubai',
    cuisine: 'Levantine',
    description: 'A wildly popular falafel and shawarma concept in Dubai known for fresh, bold Levantine street food. Crispy falafels, creamy hummus, and loaded wraps that keep locals and tourists coming back daily.',
    viralReason: 'Cult following among Dubai food lovers. Consistently ranked #1 for falafel on food delivery apps.',
    instagram: '@operationfalafel',
    emoji: '🧆',
    tags: ['Street Food', 'Falafel', 'Quick Bite', 'Affordable'],
  },
  {
    id: 'uk-01',
    name: 'Tayyabs',
    country: 'UK',
    city: 'London',
    cuisine: 'Pakistani-Punjabi',
    description: "East London's most famous Pakistani restaurant, serving sizzling lamb chops, karahi, and daal that have delighted Londoners since 1972. Always buzzing, always brilliant.",
    viralReason: "Featured in countless 'Best of London' food lists. Known for the legendary grilled lamb chops.",
    instagram: '@tayyabsrestaurant',
    emoji: '🍗',
    tags: ['Pakistani', 'Grills', 'BYOB', 'East London Institution'],
  },
  {
    id: 'uk-02',
    name: 'Dishoom Covent Garden',
    country: 'UK',
    city: 'London',
    cuisine: 'Indian Café',
    description: 'Inspired by the Irani cafés of old Bombay, Dishoom serves extraordinary breakfast, bacon naan, black dal, and biryanis in a stunning colonial-era setting. A London dining phenomenon.',
    viralReason: 'Queues around the block daily. The bacon naan roll and black dal are social media legends.',
    instagram: '@dishoom',
    emoji: '🫕',
    tags: ['Indian', 'Breakfast', 'All-day Dining', 'Iconic Queue'],
  },
  {
    id: 'sa-01',
    name: 'Al Baik',
    country: 'Saudi Arabia',
    city: 'Jeddah',
    cuisine: 'Fast Food',
    description: "Saudi Arabia's most beloved fast food chain, famous for its incredibly crispy broasted chicken and garlic sauce. Pilgrims and travellers often cite Al Baik as a highlight of visiting Saudi Arabia.",
    viralReason: 'Pilgrims carry Al Baik bags onto flights. Universally regarded as the best fried chicken in the region.',
    instagram: '@albaikofficial',
    emoji: '🍗',
    tags: ['Broasted Chicken', 'Fast Food', 'Pilgrim Favourite', 'Affordable'],
  },
  {
    id: 'pk-01',
    name: 'Bundu Khan',
    country: 'Pakistan',
    city: 'Lahore',
    cuisine: 'Pakistani BBQ',
    description: 'A Lahore legend since 1961, Bundu Khan is famous for its seekh kebabs, tikkas, and boti cooked over open charcoal grills. The smoky aroma alone draws crowds from across the city.',
    viralReason: 'A Lahore pilgrimage for food lovers worldwide. Featured in global food travel shows exploring Pakistani cuisine.',
    instagram: '@bundukhanrestaurant',
    emoji: '🔥',
    tags: ['BBQ', 'Kebabs', 'Heritage', 'Charcoal Grilled'],
  },
]

export const FILTER_COUNTRIES = [
  'All',
  'Malaysia',
  'Indonesia',
  'Turkey',
  'UAE',
  'UK',
  'Saudi Arabia',
  'Pakistan',
]
