/**
 * Curated, globally-famous halal restaurants & chains.
 * Manually vetted — update periodically.
 */
export const FEATURED_RESTAURANTS = [
  {
    id: 'f1',
    name: 'Al Baik',
    city: 'Jeddah, Saudi Arabia',
    cuisine: 'Fast Food · Fried Chicken',
    description: 'Iconic Saudi fried chicken chain beloved across the Gulf. Famous for its crispy broast chicken and garlic sauce. Halal certified.',
    website: 'https://www.albaik.com',
    emoji: '🍗',
    viral: true,
  },
  {
    id: 'f2',
    name: 'Nasi Kandar Pelita',
    city: 'Kuala Lumpur, Malaysia',
    cuisine: 'Malaysian · Nasi Kandar',
    description: '24-hour Malaysian institution for nasi kandar. JAKIM halal certified. Famous for its rich curries and roti canai.',
    website: null,
    emoji: '🍛',
    viral: true,
  },
  {
    id: 'f3',
    name: 'Zaatar w Zeit',
    city: 'Beirut, Lebanon (Middle East chain)',
    cuisine: 'Lebanese · Manakish',
    description: 'Popular Lebanese fast-casual chain serving freshly baked manakish, wraps, and mezze. All outlets are halal.',
    website: 'https://zaatarwzeit.com',
    emoji: '🫓',
    viral: true,
  },
  {
    id: 'f4',
    name: 'Warung Nasi Ampera',
    city: 'Bandung, Indonesia',
    cuisine: 'Indonesian · Sundanese',
    description: 'Iconic Sundanese rice restaurant chain serving traditional Sundanese dishes. MUI halal certified.',
    website: null,
    emoji: '🍚',
    viral: false,
  },
  {
    id: 'f5',
    name: 'Bismillah Biryani',
    city: 'Karachi, Pakistan',
    cuisine: 'Pakistani · Biryani',
    description: 'Legendary Karachi biryani house known worldwide among Pakistani diaspora. Authentic dum biryani, halal certified.',
    website: null,
    emoji: '🫕',
    viral: true,
  },
  {
    id: 'f6',
    name: 'Salam Bombay',
    city: 'London, UK',
    cuisine: 'Indian · Halal',
    description: 'Well-known halal Indian restaurant in London\'s Covent Garden. Popular with Muslim tourists visiting London.',
    website: null,
    emoji: '🍲',
    viral: false,
  },
  {
    id: 'f7',
    name: 'Ali Muthu\'s Nasi Lemak',
    city: 'Singapore',
    cuisine: 'Singaporean · Nasi Lemak',
    description: 'Famous nasi lemak stall in Geylang Serai. MUIS halal certified. Featured in numerous food guides.',
    website: null,
    emoji: '🌿',
    viral: true,
  },
  {
    id: 'f8',
    name: 'Händ Restaurant',
    city: 'Istanbul, Turkey',
    cuisine: 'Turkish · Kebab & Grills',
    description: 'Traditional Turkish kebab house near the Grand Bazaar. All meats are halal-slaughtered per Turkish Islamic standards.',
    website: null,
    emoji: '🥙',
    viral: false,
  },
]
