/**
 * Curated, globally-famous halal restaurants & chains.
 * Manually vetted — update periodically.
 * country: used for the filter buttons in FeaturedSection
 */
export const FEATURED_RESTAURANTS = [
  {
    id: 'f1',
    name: 'Al Baik',
    city: 'Jeddah, Saudi Arabia',
    country: 'Saudi Arabia',
    cuisine: 'Fast Food · Fried Chicken',
    description: 'Iconic Saudi fried chicken chain beloved across the Gulf. Famous for its crispy broast chicken and garlic sauce. Halal certified.',
    website: 'https://www.albaik.com',
    emoji: '🍗',
    viral: true,
  },
  {
    id: 'f2',
    name: 'Nasi Kandar Pelita',
    city: 'Kuala Lumpur, Malaysia',
    country: 'Malaysia',
    cuisine: 'Malaysian · Nasi Kandar',
    description: '24-hour Malaysian institution for nasi kandar. JAKIM halal certified. Famous for its rich curries and roti canai.',
    website: null,
    emoji: '🍛',
    viral: true,
  },
  {
    id: 'f3',
    name: 'Zaatar w Zeit',
    city: 'Beirut, Lebanon (Middle East chain)',
    country: 'UAE',
    cuisine: 'Lebanese · Manakish',
    description: 'Popular Lebanese fast-casual chain serving freshly baked manakish, wraps, and mezze. All outlets are halal.',
    website: 'https://zaatarwzeit.com',
    emoji: '🫓',
    viral: true,
  },
  {
    id: 'f4',
    name: 'Warung Nasi Ampera',
    city: 'Bandung, Indonesia',
    country: 'Indonesia',
    cuisine: 'Indonesian · Sundanese',
    description: 'Iconic Sundanese rice restaurant chain serving traditional Sundanese dishes. MUI halal certified.',
    website: null,
    emoji: '🍚',
    viral: false,
  },
  {
    id: 'f5',
    name: 'Bismillah Biryani',
    city: 'Karachi, Pakistan',
    country: 'Pakistan',
    cuisine: 'Pakistani · Biryani',
    description: 'Legendary Karachi biryani house known worldwide among Pakistani diaspora. Authentic dum biryani, halal certified.',
    website: null,
    emoji: '🫕',
    viral: true,
  },
  {
    id: 'f6',
    name: 'Tayyabs',
    city: 'London, UK',
    country: 'UK',
    cuisine: 'Pakistani · Grills',
    description: 'East London institution since 1972. Famous for its dry-spiced lamb chops and karahi. Fully halal, always packed.',
    website: 'https://www.tayyabs.co.uk',
    emoji: '🥩',
    viral: true,
  },
  {
    id: 'f7',
    name: 'Nasi Lemak Antarabangsa',
    city: 'Kuala Lumpur, Malaysia',
    country: 'Malaysia',
    cuisine: 'Malaysian · Nasi Lemak',
    description: 'Beloved 24-hour nasi lemak stall in Chow Kit, KL. JAKIM halal certified. A must-try for any KL visitor.',
    website: null,
    emoji: '🌿',
    viral: true,
  },
  {
    id: 'f8',
    name: 'Çiya Sofrası',
    city: 'Istanbul, Turkey',
    country: 'Turkey',
    cuisine: 'Turkish · Anatolian',
    description: 'Legendary Kadıköy restaurant serving rare Anatolian recipes. Featured in countless food magazines. All halal.',
    website: 'https://ciya.com.tr',
    emoji: '🥙',
    viral: true,
  },
  {
    id: 'f9',
    name: 'Al Fanar Restaurant',
    city: 'Dubai, UAE',
    country: 'UAE',
    cuisine: 'Emirati · Traditional',
    description: 'Authentic Emirati cuisine in a charming lighthouse setting. Must-try machboos and luqaimat. Halal certified.',
    website: 'https://www.alfanarrestaurant.com',
    emoji: '🏮',
    viral: false,
  },
  {
    id: 'f10',
    name: 'Operation Falafel',
    city: 'Dubai, UAE',
    country: 'UAE',
    cuisine: 'Lebanese · Street Food',
    description: 'Hugely popular Dubai chain for crispy falafel wraps and mezze. Halal certified. Multiple UAE locations.',
    website: 'https://operationfalafel.com',
    emoji: '🧆',
    viral: true,
  },
  {
    id: 'f11',
    name: 'Sate Khas Senayan',
    city: 'Jakarta, Indonesia',
    country: 'Indonesia',
    cuisine: 'Indonesian · Satay',
    description: 'Jakarta\'s most iconic satay restaurant, serving since 1974. MUI halal certified. Tender chicken and beef skewers.',
    website: null,
    emoji: '🍢',
    viral: true,
  },
  {
    id: 'f12',
    name: 'Dishoom',
    city: 'London, UK',
    country: 'UK',
    cuisine: 'Indian · Bombay Café',
    description: 'Award-winning Bombay-style café with outlets across the UK. Breakfast and dinner queues are legendary. Halal chicken.',
    website: 'https://www.dishoom.com',
    emoji: '🍲',
    viral: true,
  },
]

/** All unique countries in display order for the filter buttons */
export const FILTER_COUNTRIES = [
  'All',
  'Malaysia',
  'Indonesia',
  'Turkey',
  'UAE',
  'UK',
  'Saudi Arabia',
  'Pakistan',
]
